export const GET_RANDOM_QUESTION = "GET_RANDOM_QUESTION";
export const HANDLE_WRONG_ANSWER = "HANDLE_WRONG_ANSWER";
export const HANDLE_CORRECT_ANSWER = "HANDLE_CORRECT_ANSWER";
export const PLAY_NEXT = "PLAY_NEXT";
export const GAME_OVER = "GAME_OVER";
export const PLAY_AGAIN = "PLAY_AGAIN";
export const START_GAME = "START_GAME";
export const SET_MODE = "SET_MODE";
